on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.qwik-build.outputs.page-url }}

    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: 🚚 Get latest code
      uses: actions/checkout@v2.5.0

    - name: Clean install dependencies
      working-directory: web
      run: npm ci

    - name: Build app
      working-directory: web
      run: npm run build && npm run build.ssg && npm run ssg
